- name: Ansible replace
  hosts: stapp01,stapp02,stapp03
  become: yes
  tasks:
    - name: blog.txt replacement
      replace:
        path: /opt/sysops/blog.txt
        regexp: "xFusionCorp"
        replace: "Nautilus"
      when: inventory_hostname == "stapp01"
    - name: story.txt replacement
      replace:
        path: /opt/sysops/story.txt
        regexp: "Nautilus"
        replace: "KodeKloud"
      when: inventory_hostname == "stapp02"
    - name: media.txt replacement
      replace:
        path: /opt/sysops/media.txt
        regexp: "KodeKloud"
        replace: "xFusionCorp Industries"
      when: inventory_hostname == "stapp03"
